version: "2"

run:
  timeout: 3m
  go: "1.25"
  version: "v2.11.4"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - gofmt
    - goimports

issues:
  exclude-dirs:
    - test/e2e
